apiVersion: v1
kind: Service
metadata:
  name: springapp-service
spec:
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 80 # local에서 접속하는 port ###########################################
      targetPort: 8900 # springapp이 실행되는 port ###########################################
  type: LoadBalancer  # LoadBalancer 유형을 사용하여 외부 접근 가능
